version: '3'
services:
  hazelcast:
    image: hazelcast/hazelcast:latest
    ports:
      - "5701:5701"
    environment:
      - JAVA_OPTS=-Dhazelcast.local.publicAddress=127.0.0.1:5701
  management-center:
    image: hazelcast/management-center:latest
    ports:
      - "8080:8080"
