apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: transaction-subscription
spec:
  topic: transaction_topic
  route: /transaction/complete
  pubsubname: pubsub
scopes:
  - hazelcast-demo-consumer